def field(key, label, field_type, options=None, affects_price=False, depends_on=None):
    """depends_on: optional {"field": <spec_key>, "equals": <value>} or {"field": <spec_key>, "truthy": True}.
    Used by the frontend spec editor to progressively disclose fields only when relevant
    (e.g. Custom Coverage % only shown when Coverage Type = Custom)."""
    return {
        "key": key,
        "label": label,
        "type": field_type,
        "options": options or [],
        "affects_price": affects_price,
        "depends_on": depends_on,
    }


COMMON_FIELDS = [
    field("width_inches", "Width (inches)", "number", affects_price=True),
    field("height_inches", "Height (inches)", "number", affects_price=True),
    field("unit_of_measure", "Unit of Measure", "select", ["inches", "feet"], True),
    field("quantity_discounts_note", "Quantity discounts apply automatically from Pricing Foundation", "note"),
    field("artwork_ready", "Artwork Already Ready", "toggle", affects_price=True),
    field("artwork_needed", "Artwork Needed (if not ready)", "toggle", affects_price=True, depends_on={"field": "artwork_ready", "equals": False}),
    field("design_complexity", "Design Complexity", "select", ["simple", "medium", "complex", "extreme"], True, depends_on={"field": "artwork_ready", "equals": False}),
    field("install_required", "Install Required", "toggle", affects_price=True),
    field("install_complexity", "Install Complexity", "select", ["easy", "medium", "difficult", "high_risk"], True, depends_on={"field": "install_required", "truthy": True}),
    field("rush_order", "Rush Order", "toggle", affects_price=True),
]

CATEGORY_SCHEMAS = {
    "banners": [
        *COMMON_FIELDS,
        field("banner_material_key", "Banner Material", "select", ["banner_13oz", "banner_18oz", "banner_mesh", "banner_blockout", "banner_fabric", "banner_custom"], True),
        field("banner_double_sided", "Double-Sided?", "select", ["no", "same", "different"], True),
        field("banner_laminate", "Laminate / Coating", "toggle", affects_price=True),
        field("banner_laminate_type_key", "Laminate Type", "select", ["banner_laminate_coating", "banner_laminate_matte"], True, depends_on={"field": "banner_laminate", "truthy": True}),
        field("banner_hems", "Hems", "select", ["none", "standard", "reinforced"], True),
        field("banner_grommets", "Grommets", "select", ["none", "corners", "every_2ft", "every_3ft", "custom"], True),
        field("banner_grommet_count", "Custom Grommet Count", "number", affects_price=True, depends_on={"field": "banner_grommets", "equals": "custom"}),
        field("banner_pole_pockets", "Pole Pockets", "select", ["none", "top", "top_and_bottom", "side_pockets"], True),
        field("banner_reinforced_corners", "Reinforced Corners", "toggle", affects_price=True),
        field("banner_wind_slits", "Wind Slits", "toggle", affects_price=True),
        field("banner_specialty_sewing", "Specialty Sewing", "toggle", affects_price=True),
        field("banner_hardware_keys", "Hardware (comma-separated keys)", "text", affects_price=True),
        field("banner_use_type", "Use Type", "select", ["outdoor", "indoor", "pole_banner", "backwall_step_repeat", "event_display"], True),
    ],
    "rigid_signs": [
        *COMMON_FIELDS,
        field("substrate_type_key", "Substrate Type", "select", ["coroplast_4mm", "pvc_3mm", "acm_dibond_3mm", "aluminum_040", "acrylic_1_8", "custom_other_substrate"], True),
        field("graphic_method", "Graphic Method", "select", ["direct_print", "mounted_print", "cut_vinyl_applied"], True),
        field("sidedness", "Single or Double Sided", "select", ["single", "double"], True),
        field("double_sided_art", "Double-Sided Art", "select", ["same", "different"], True, depends_on={"field": "sidedness", "equals": "double"}),
        field("shape_type", "Shape", "select", ["rectangle", "circle", "custom_cut"], True),
        field("thickness", "Thickness", "select", ["3mm", "6mm", "10mm", "0.040", "0.063", "0.080", "1/4", "1/2"], True),
        field("finish_quality", "Finish Quality", "select", ["standard", "premium"], True),
        field("protective_finish", "Protective Finish", "toggle", affects_price=True),
        field("protective_finish_type", "Finish Type", "select", ["rigid_finish_standard", "rigid_finish_premium"], True, depends_on={"field": "protective_finish", "truthy": True}),
        field("hardware_included", "Hardware Included", "toggle", affects_price=True),
        field("hardware_type", "Hardware Type", "text", affects_price=True, depends_on={"field": "hardware_included", "truthy": True}),
        field("drill_prep_required", "Drill Prep Required", "toggle", affects_price=True),
    ],
    "cut_vinyl": [
        *COMMON_FIELDS,
        field("vinyl_type_key", "Vinyl Type", "select", ["oracal_651", "oracal_751", "reflective_vinyl", "wall_vinyl", "specialty_custom_vinyl"], True),
        field("num_colors", "Number of Colors", "number", affects_price=True),
        field("weeding_complexity", "Weeding Complexity", "select", ["simple", "detailed", "intricate"], True),
        field("masking_required", "Masking / Application Tape", "toggle", affects_price=True),
        field("use_type", "Use Type", "select", ["indoor", "outdoor", "vehicle", "wall"], True),
    ],
    "digital_print": [
        *COMMON_FIELDS,
        field("print_media_key", "Print Media Type", "select", ["printable_adhesive_vinyl", "poster_paper", "canvas", "backlit_film", "wall_graphic_media", "specialty_print_media"], True),
        field("ink_coverage_percent", "Ink Coverage %", "number", affects_price=True),
        field("print_quality_mode", "Print Quality", "select", ["draft", "production", "premium"], True),
        field("laminate", "Laminate Required", "toggle", affects_price=True),
        field("laminate_type_key", "Laminate Type", "select", ["print_laminate_gloss", "print_laminate_matte"], True, depends_on={"field": "laminate", "truthy": True}),
        field("mounted_to_substrate", "Mount to Substrate", "toggle", affects_price=True),
        field("substrate_material_key", "Mount Substrate", "select", ["acm_dibond_3mm", "coroplast_4mm", "pvc_3mm"], True, depends_on={"field": "mounted_to_substrate", "truthy": True}),
        field("contour_cut_type", "Contour Cut", "select", ["none", "simple_shape", "complex_shape"], True),
        field("piece_separation_required", "Piece Separation Required", "toggle", affects_price=True),
        field("separated_piece_count", "Number of Pieces", "number", affects_price=True, depends_on={"field": "piece_separation_required", "truthy": True}),
        field("trim_finish_type", "Trim / Finish", "select", ["none", "rounded_corners", "hem_and_weld"], True),
        field("file_cleanup_needed", "File Cleanup Needed", "toggle", affects_price=True),
        field("include_setup_fee", "Include Setup Fee", "toggle", affects_price=True),
    ],
    "vehicle_wrap": [
        field("vehicle_type", "Vehicle Type", "select", ["sedan", "suv", "pickup", "van_cargo", "sprinter_van", "box_truck_16", "trailer", "semi"], True),
        field("coverage_type", "Coverage Type", "select", ["spot", "partial", "half", "full", "custom"], True),
        field("custom_coverage_percent", "Custom Coverage %", "number", affects_price=True, depends_on={"field": "coverage_type", "equals": "custom"}),
        field("estimated_vehicle_sqft", "Override Estimated Sqft", "number", affects_price=True),
        field("wrap_material_key", "Wrap Material", "select", ["wrap_standard_calendared", "wrap_premium_cast", "wrap_cast_film", "wrap_reflective", "wrap_specialty_media"], True),
        field("wrap_laminate_required", "Laminate Required", "toggle", affects_price=True),
        field("wrap_laminate_type_key", "Laminate Type", "select", ["wrap_laminate_gloss", "wrap_laminate_matte"], True, depends_on={"field": "wrap_laminate_required", "truthy": True}),
        field("window_perf_included", "Window Perf Included", "toggle", affects_price=True),
        field("window_perf_scope", "Window Perf Scope", "select", ["rear", "side", "full"], True, depends_on={"field": "window_perf_included", "truthy": True}),
        field("surface_prep_level", "Surface Prep Level", "select", ["none", "light", "heavy"], True),
        field("removal_scope", "Old Graphics Removal", "select", ["none", "partial", "full"], True),
        field("install_required", "Install Required", "toggle", affects_price=True),
        field("install_difficulty_level", "Install Difficulty", "select", ["easy", "medium", "difficult", "extreme"], True, depends_on={"field": "install_required", "truthy": True}),
        field("seam_complexity", "Seam Complexity", "select", ["basic", "moderate", "complex"], True, depends_on={"field": "install_required", "truthy": True}),
        field("second_installer_required", "Second Installer Required", "toggle", affects_price=True, depends_on={"field": "install_required", "truthy": True}),
        field("artwork_ready", "Artwork Already Ready", "toggle", affects_price=True),
        field("artwork_needed", "Artwork Needed", "toggle", affects_price=True, depends_on={"field": "artwork_ready", "equals": False}),
        field("design_complexity", "Design Complexity", "select", ["simple", "medium", "complex", "extreme"], True, depends_on={"field": "artwork_ready", "equals": False}),
        field("rush_order", "Rush Order", "toggle", affects_price=True),
    ],
    "services": [
        field("service_type", "Service Type", "text", affects_price=True),
        field("services_billing_unit", "Billing Unit", "select", ["hour", "flat", "piece", "sqft", "linear_foot", "mile", "trip", "day"], True),
        field("services_labor_role", "Labor Role", "select", ["production", "design", "install"], True),
        field("services_complexity", "Complexity", "select", ["simple", "medium", "complex"], True),
        field("estimated_hours", "Estimated Hours", "number", affects_price=True, depends_on={"field": "services_billing_unit", "equals": "hour"}),
        field("num_workers", "Number of Workers", "number", affects_price=True),
        field("services_flat_fee", "Flat Fee ($)", "number", affects_price=True, depends_on={"field": "services_billing_unit", "equals": "flat"}),
        field("services_unit_rate_override", "Unit Rate Override ($)", "number", affects_price=True),
        field("services_minimum_override", "Minimum Charge Override ($)", "number", affects_price=True),
        field("services_travel_required", "Travel Required", "toggle", affects_price=True),
        field("services_travel_miles", "Travel Miles", "number", affects_price=True, depends_on={"field": "services_travel_required", "truthy": True}),
        field("services_trip_charge_applies", "Trip Charge Applies", "toggle", affects_price=True),
        field("services_equipment_required", "Equipment Rental Required", "toggle", affects_price=True),
        field("services_equipment_type", "Equipment Type", "text", affects_price=True, depends_on={"field": "services_equipment_required", "truthy": True}),
        field("services_equipment_days", "Equipment Days", "number", affects_price=True, depends_on={"field": "services_equipment_required", "truthy": True}),
        field("services_equipment_hours", "Equipment Hours", "number", affects_price=True, depends_on={"field": "services_equipment_required", "truthy": True}),
        field("services_subcontracted", "Subcontracted", "toggle", affects_price=True),
        field("services_subcontract_cost", "Subcontractor Cost ($)", "number", affects_price=True, depends_on={"field": "services_subcontracted", "truthy": True}),
        field("services_permit_external_fee", "Permit / External Fee ($)", "number", affects_price=True),
        field("rush_order", "Rush Order", "toggle", affects_price=True),
    ],
    "apparel": [
        field("apparel_product_type", "Product Type", "select", ["short_sleeve_tee", "hoodie", "polo", "standard_cap", "premium_cap"], True),
        field("apparel_brand_style_key", "Brand / Style", "select", ["blank_ss_gildan_5000", "blank_ss_bella_3001", "blank_hd_gildan_18500", "blank_hat_standard"], True),
        field("apparel_decoration_method", "Decoration Method", "select", ["htv", "screen_print", "dtf", "embroidery", "dtg"], True),
        field("apparel_placement_set", "Placement", "select", ["front", "back", "front_and_back", "sleeve"], True),
        field("apparel_num_colors", "Number of Colors", "number", affects_price=True, depends_on={"field": "apparel_decoration_method", "equals": "screen_print"}),
        field("apparel_stitch_count", "Stitch Count", "number", affects_price=True, depends_on={"field": "apparel_decoration_method", "equals": "embroidery"}),
        field("customer_supplied", "Customer-Supplied Blanks", "toggle", affects_price=True),
        field("size_xs", "XS Qty", "number", affects_price=True), field("size_s", "S Qty", "number", affects_price=True),
        field("size_m", "M Qty", "number", affects_price=True), field("size_l", "L Qty", "number", affects_price=True),
        field("size_xl", "XL Qty", "number", affects_price=True), field("size_2xl", "2XL Qty", "number", affects_price=True),
        field("size_3xl", "3XL Qty", "number", affects_price=True),
        field("apparel_plus_size_count", "Plus-Size Piece Count (2XL+)", "number", affects_price=True),
        field("apparel_custom_name_number", "Custom Name/Number", "toggle", affects_price=True),
        field("apparel_custom_name_number_count", "Name/Number Count", "number", affects_price=True, depends_on={"field": "apparel_custom_name_number", "truthy": True}),
        field("apparel_specialty_finish", "Specialty Finish", "toggle", affects_price=True),
        field("apparel_bag_and_fold", "Bag & Fold", "toggle", affects_price=True),
        field("artwork_ready", "Artwork Already Ready", "toggle", affects_price=True),
        field("artwork_needed", "Artwork Needed", "toggle", affects_price=True, depends_on={"field": "artwork_ready", "equals": False}),
        field("design_complexity", "Design Complexity", "select", ["simple", "medium", "complex", "extreme"], True, depends_on={"field": "artwork_ready", "equals": False}),
        field("rush_order", "Rush Order", "toggle", affects_price=True),
    ],
    "promo_misc": [
        field("promo_product_type", "Product Type", "text", affects_price=True),
        field("unit_cost_minor", "Unit Cost (cents)", "number", affects_price=True),
        field("markup_percent", "Markup % Override", "number", affects_price=True),
        field("include_setup_fee", "Include Setup Fee", "toggle", affects_price=True),
        field("rush_order", "Rush Order", "toggle", affects_price=True),
    ],
    "custom": [
        field("unit_cost_minor", "Unit Cost (cents)", "number", affects_price=True),
        field("estimated_hours", "Estimated Labor Hours", "number", affects_price=True),
        field("markup_percent", "Markup % Override", "number", affects_price=True),
        field("override_enabled", "Manual Price Override", "toggle", affects_price=True),
        field("price_override", "Override Price (per unit, $)", "number", affects_price=True, depends_on={"field": "override_enabled", "truthy": True}),
        field("manual_description", "Manual Description", "textarea"),
        field("rush_order", "Rush Order", "toggle", affects_price=True),
    ],
}


def category_schema(category: str) -> dict:
    return {"category": category, "fields": CATEGORY_SCHEMAS.get(category, CATEGORY_SCHEMAS["custom"])}
