export const seedCommunityPosts = [
  {
    id: "COMM-SEED-BUG",
    title: "Wrap proof approval should show customer comments in production",
    body: "When a customer requests a proof revision, the production team needs those comments visible before printing.",
    category: "bug_report",
    status: "open",
    author_name: "Preview Shop",
    upvotes: 4,
    replies: [{ id: "R1", author_name: "SignGuy AI", body: "Queued for Wrap It! production handoff review.", is_official: true, created_at: new Date().toISOString() }],
    is_pinned: true,
    is_answered: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "COMM-SEED-FEATURE",
    title: "Add customer-facing install checklist",
    body: "It would help to send customers a checklist before vehicle drop-off or site install.",
    category: "feature_request",
    status: "in_progress",
    author_name: "Shop Owner",
    upvotes: 7,
    replies: [],
    is_pinned: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "COMM-SEED-QUESTION",
    title: "Where should shared artwork live?",
    body: "Should artwork be on the customer, the order, or the asset library?",
    category: "question",
    status: "open",
    author_name: "Installer",
    upvotes: 2,
    replies: [],
    is_pinned: false,
    created_at: new Date().toISOString(),
  },
];

export const seedNotes = [
  {
    id: "NOTE-SEED-ORDER",
    title: "Shared order context",
    body: "Production, color/brand, install/location, and design notes should be stored once and inherited by downstream order items.",
    scope: "orders",
    visibility: "internal",
    status: "open",
    priority: "high",
    tags: ["shared-context", "orders"],
    created_by: "System",
    created_at: new Date().toISOString(),
  },
  {
    id: "NOTE-SEED-WRAP",
    title: "Wrap It! should reuse core customers",
    body: "Wrap projects must continue linking to shared customer records so quotes, orders, invoices, and portal records have the same source.",
    scope: "wrap-it",
    visibility: "internal",
    status: "open",
    priority: "high",
    tags: ["wrap-it", "customers"],
    created_by: "System",
    created_at: new Date().toISOString(),
  },
];

export const fallbackAiTools = [
  ["text_to_image", "AI Image Concept Creator", "Design", "High", "Create AI-generated concept images from text direction."],
  ["idea_brainstormer", "Idea Brainstormer", "Branding", "Low", "Generate names, slogans, campaign ideas, and creative concepts."],
  ["permit_research", "Sign Permit Research", "Business", "Medium", "Draft permit research guidance from city, sign type, and zoning context."],
  ["photo_enhancer", "Photo Enhancer Analyzer", "Design", "Medium", "Assess print readiness, scaling risks, and enhancement needs."],
  ["image_vectorizer", "Vectorization Analyzer", "Design", "Medium", "Review vectorization difficulty, cleanup needs, and production advice."],
  ["font_identifier", "Font Identifier", "Design", "Medium", "Analyze text artwork and suggest likely fonts and alternatives."],
  ["ai_sign_designer", "AI Sign Designer", "Design", "High", "Create sign concept guidance and visual concept direction."],
  ["ai_banner_designer", "AI Banner Designer", "Design", "High", "Create banner layout guidance and concept direction."],
  ["mockup_creator", "Mockup Creator", "Design", "High", "Generate realistic mockup scene direction for signs, wraps, and displays."],
  ["vehicle_wrap_mockup", "Vehicle Wrap Mockup Generator", "Wraps", "High", "Generate vehicle wrap mockup direction by vehicle type and angle."],
  ["logo_creator", "Logo Creator", "Branding", "High", "Generate original logo concept directions from brand inputs."],
  ["branding_kit_generator", "Branding Kit Generator", "Branding", "Medium", "Create brand-system guidance with colors, typography, voice, and usage rules."],
  ["business_copywriter", "Business Copywriter", "Marketing", "Medium", "Write service, homepage, ad, and marketing copy."],
  ["document_composer", "Document Composer", "Documents", "Medium", "Draft proposals, scopes of work, payment letters, and project briefs."],
  ["pricing_intelligence", "Pricing Intelligence Assistant", "Pricing", "Medium", "Review pricing scenarios and recommend margin, markup, and positioning improvements."],
  ["blog_creator", "Blog Article Creator", "Marketing", "Medium", "Generate articles, titles, meta descriptions, CTAs, and image ideas."],
  ["completed_job_post", "Completed Job Post Creator", "Marketing", "Medium", "Turn completed-job details into social captions, hashtags, and post tips."],
  ["social_pack_generator", "Social Media Pack Generator", "Marketing", "Medium", "Produce batches of social content ideas and post suggestions."],
  ["content_calendar", "Content Calendar Creator", "Marketing", "Medium", "Build a content calendar with themes, timing, and ideas."],
  ["campaign_builder", "Campaign Builder", "Marketing", "Medium", "Design a campaign strategy with audience, content, channels, and metrics."],
  ["wrap_cost_calculator", "Vehicle Wrap Cost Calculator", "Wraps", "Medium", "Create AI-assisted wrap pricing breakdowns and quote ranges."],
  ["email_templates", "Email Templates Generator", "Communication", "Medium", "Generate reusable quote, invoice, approval, update, and follow-up email templates."],
  ["review_responder", "Review Responder", "Communication", "Low", "Draft professional responses to customer reviews."],
  ["assistant_chat", "AI Business Assistant", "Assistant", "Medium", "Answer sign-shop business questions and summarize operational context."],
].map(([id, name, category, intensity, description]) => ({ id, name, category, intensity, description }));
